services:
  gpodder:
    container_name: opodsync
#    network_mode: host
    build:
      context: ./
      dockerfile: Dockerfile
    command: php -d max_execution_time=0 -S 0.0.0.0:8080
    working_dir: /var/www/server

    # 1. 자동 재시작 및 포트 지정 (network_mode: host는 제거)
    restart: always
    ports:
      - 8080:8080  

    # 2. 타임존 및 환경변수 설정 (수동 run 명령 반영)
    environment:
      - TZ=Asia/Seoul
    volumes:
      - type: bind
        source: ./server/data
        target: /var/www/server/data
      - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-timeout.ini
    hostname: opodsync.localhost
